### PR TITLE
Check isComposing for send shortcut for IME users

### PR DESCRIPTION
**Pull request by hanayashiki**
Currently for the input box, the input box still sends message  even if the user just presses enter for the IME.

图片

Checking `!e.isComposing` in `isSendShortcutPressed` stops the input box from responding to that.

### CODE REVIEW

**Comment by morethanwords** [comment]
Thank you for contribution! Could you please revert the 'Rebuild' commit, so I'll be able to merge it?

**Comment by hanayashiki** [comment]
> Thank you for contribution! Could you please revert the 'Rebuild' commit, so I'll be able to merge it?

Okay. Maybe we shouldnt include build into git anymore?

**Comment by morethanwords** [comment]
Thanks! Builds are needed on git just to update application on live.

**Comment by hanayashiki** [comment]
> Thanks! Builds are needed on git just to update application on live.

Can't believe a company with 500 million users don't have a proper CI service

**Comment by morethanwords** [comment]
Why do you think we need it?

**Comment by hanayashiki** [comment]
> Why do you think we need it?

well, the industry convention?

**Comment by morethanwords** [comment]
> > Why do you think we need it?
> 
> 
> 
> well, the industry convention?
> 
> 

I've been developing it alone since the first stage of contest, and I don't think that something is going to change. I don't want to complicate anything, so it's the easiest way to update it.

**Comment by hanayashiki** [comment]
Yeah, the pull requesters can just don't add "public/*" so you'll be the sole builder (avoiding conflicts). That works

**Pull request merged**
